server:
  port: 9003
spring:
  application:
    name: service-article #指定服务名
  boot:
    admin:
      client:
        instance:
          service-base-url: http://localhost:9003

com:
  madaoo:
    aopPointcutExpression: execution (* com.madaoo.article..*.*(..))



hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: false
        isolation:
          strategy: SEMAPHORE