server:
  port: 9009
spring:
  application:
    name: server-config #指定服务名
  rabbitmq:
    host: 39.108.191.56
    username: admin
    password: admin
    port: 5672


# 消息总线BUS自动刷新配置文件
management: #暴露触发消息总线的地址
  endpoints:
    web:
      exposure:
        include: bus-refresh
  security:
    enabled: false # 刷新时，关闭安全验证


---
#dev
spring:
  profiles: dev

eureka:
  client: #客户端注册进eureka服务列表内
    service-url:
      #defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
      defaultZone:  http://localhost:5000/eureka  #单机版
  instance:
    instance-id: ${spring.cloud.client.ip-address}:${server.port} # 为注册的这个服务起个别名
    prefer-ip-address: true     #使用ip进行注册
    # 注册中心跳转到swagger接口
    status-page-url-path:  /swagger-ui.html
    # #绑定客户端的ip而不是主机号
    hostname: ${spring.cloud.client.ip-address}   # ${spring.cloud.client.ip-address} 参考https://blog.csdn.net/xichenguan/article/details/76632033


---

# production
spring:
  profiles: prod

eureka:
  client: #客户端注册进eureka服务列表内
    service-url:
      #defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
      defaultZone:  http://39.108.191.56:5000/eureka  #单机版
  instance:
    instance-id: http://39.108.191.56:${server.port} # 为注册的这个服务起个别名
    prefer-ip-address: true     #使用ip进行注册
    # 注册中心跳转到swagger接口
    status-page-url-path:  http://39.108.191.56:${server.port}/swagger-ui.html
    # #绑定客户端的ip而不是主机号
    hostname: 39.108.191.56   # ${spring.cloud.client.ip-address} 参考https://blog.csdn.net/xichenguan/article/details/76632033

