server:
  port: 9009
spring:
  application:
    name: server-config #指定服务名
  rabbitmq:
    host: 39.108.191.56
    username: admin
    password: admin
    port: 5672
  cloud:
    config:
      server:
        git:
          uri: https://github.com/GuoGuang0536/youyd_config.git
          searchPaths: dev
          default-label: master
          username: GuoGuang0536@gmail.com
          password: '{cipher}AQByObofDhY9uTHDkgdQGKPsY8n/zNY4Ob7Y+e7F7qC2byK8OebsVrmZOeycgki1x8/RTl/4RRBmjLdriBIUkAMt0bAIKK21GDNDGkiSlhSy7RmBM3BHTlKDs9AR72aVjdFQh6W6p6t0vnoEPTGi8GYXAW52QO+e3Xwmjs7Qxr54/NE9MjM1ImlYJOYrLY5ciRInkRZKF2ZtJNM+Kseu0puwjieXpJhdNClZJtosdUagaZxwP3sP63SS+UYnmwyyF1PIc3EAqymH++JntlEWvUqM7mLeFs+lfd7iQHTjOB0RjLDLf4JYT/ea7C1pz2cHYcsWZeF1ui1iOJyBaRhkLPlFAsn0S6PvSp20IzvHYw5lv/Z92ENqzSWhhz5M54xycuc='
    bus:
      enabled: true # 开启消息跟踪

eureka:
  client: #客户端注册进eureka服务列表内
    service-url:
      #defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
      defaultZone:  http://localhost:5000/eureka  #单机版
  instance:
    instance-id: ${spring.cloud.client.ip-address}:${server.port} # 为注册的这个服务起个别名
    prefer-ip-address: true     #使用ip进行注册
    # 注册中心跳转到swagger接口
    status-page-url-path:  /swagger-ui.html
    # #绑定客户端的ip而不是主机号
    hostname: ${spring.cloud.client.ip-address}   # ${spring.cloud.client.ip-address} 参考https://blog.csdn.net/xichenguan/article/details/76632033
