server:
  port: 9003
spring:
  application:
    name: service-article #指定服务名

com:
  codeway:
    aopPointcutExpression: execution (* com.codeway.article..*.*(..))



hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: false
        isolation:
          strategy: SEMAPHORE